#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
omp opencode-go usage 紧凑格式 —— 自愈安装器

背景
  omp 升级会用新文件覆盖 dist/cli.js,导致手工打的 usage segment
  补丁(紧凑格式 `0%-8%-4%`)丢失。本脚本一次性解决:

    1) 自动定位真实 cli.js(bun 全局安装,兼容已装 wrapper 的环境);
    2) 把内置 usage segment 渲染改为紧凑格式:5h-7d-月 三窗口百分比,
       `-` 连接,输出如 `0%-8%-4%`(无内部符号依赖,升级后仍可重打);
    3) 在 PATH 优先位置安装自愈 wrapper(`~/.local/bin/omp` 优先):
       每次启动检测补丁标记,缺失则自动重打,再 exec 真 omp;
    4) 幂等,可重复运行;换环境后重跑一次即可。

用法
  python3 install-omp-usage.py [--bin-dir DIR] [--cli PATH]

  --bin-dir   wrapper 安装目录(默认自动:取 PATH 中优先于 omp 的可写目录,
              首选 ~/.local/bin)
  --cli       显式指定 cli.js 路径(默认自动检测)

说明
  补丁逻辑唯一事实来源是下方 apply_patch():wrapper 内嵌代码由
  inspect.getsource() 从本函数生成,避免两处维护漂移。

  失效降级:若 omp 大幅重构导致定位不到 usage segment,补丁安全失败
  (wrapper 打印警告并按未补丁版启动),不会崩溃。
"""

import argparse
import inspect
import os
import re
import shutil
import stat
import subprocess
import sys

MARK = "omp-usage-compact"  # 与 apply_patch() replacement 内注释必须一致

# ---------------------------------------------------------------- patch


def apply_patch(src: str) -> str:
    """把内置 usage segment 渲染替换为紧凑格式。输入/输出均为 cli.js 全文。"""
    m = re.search(r'id:"usage",render\([^)]*\)\{', src)
    if not m:
        raise ValueError("usage segment not found (omp structure changed?)")
    open_brace = src.rfind("{", 0, m.start())
    if open_brace < 0:
        raise ValueError("usage segment object start not found")
    depth = 0
    i = open_brace
    while i < len(src):
        c = src[i]
        if c == "{":
            depth += 1
        elif c == "}":
            depth -= 1
            if depth == 0:
                break
        i += 1
    if i >= len(src):
        raise ValueError("unbalanced braces in usage segment")
    replacement = (
        '{id:"usage",render(_i){let n=_i.usage;'
        'if(!n||!n.fiveHour&&!n.sevenDay&&!n.monthly)return{content:"",visible:!1};'
        "let h=[];"
        'if(n.fiveHour)h.push(`${Math.round(n.fiveHour.percent)}%`);'
        'if(n.sevenDay)h.push(`${Math.round(n.sevenDay.percent)}%`);'
        'if(n.monthly)h.push(`${Math.round(n.monthly.percent)}%`);'
        # 注释内的 MARK 是 wrapper 的"已补丁"检测标记,勿改
        'return{content:h.join("-")/*omp-usage-compact*/,visible:!0}}}'
    )
    return src[:open_brace] + replacement + src[i + 1 :]


# ---------------------------------------------------------------- locate


def is_cli(path: str) -> bool:
    if not path or not os.path.isfile(path):
        return False
    try:
        with open(path, "rb") as f:
            head = f.read(256)
        size = os.path.getsize(path)
    except OSError:
        return False
    # 真 cli.js: bun shebang + 打包产物体积;wrapper/bash 脚本不满足
    return head.startswith(b"#!/usr/bin/env bun") and size > 1024 * 1024


def find_cli(explicit: str | None) -> str:
    if explicit:
        if not is_cli(explicit):
            sys.exit(f"error: --cli {explicit} 不是有效的 cli.js(缺少 id:\"usage\" 特征)")
        return os.path.realpath(explicit)

    candidates: list[str] = []

    # 1) PATH 中的 omp:若本身就是 cli.js(未装 wrapper 的 bun shim)直接用
    w = shutil.which("omp")
    if w:
        candidates.append(os.path.realpath(w))

    # 2) 常见 bun 安装位置(覆盖 wrapper 已装、which 被劫持的情况)
    bun_root = os.environ.get("BUN_INSTALL") or os.path.expanduser("~/.bun")
    candidates.append(
        os.path.realpath(os.path.join(bun_root, "bin", "omp"))
    )
    candidates.append(
        os.path.join(
            bun_root,
            "install",
            "global",
            "node_modules",
            "@oh-my-pi",
            "pi-coding-agent",
            "dist",
            "cli.js",
        )
    )

    seen: set[str] = set()
    for c in candidates:
        r = os.path.realpath(c)
        if r in seen:
            continue
        seen.add(r)
        if is_cli(r):
            return r
    sys.exit(
        "error: 未找到 omp 的 cli.js。请确认 omp 已安装(bun 全局安装),"
        "或用 --cli 显式指定路径。"
    )


# ---------------------------------------------------------------- wrapper


def wrapper_script(cli: str) -> str:
    """生成自愈 wrapper(bash)。补丁逻辑从 apply_patch 源码内嵌,单一事实来源。"""
    patch_src = inspect.getsource(apply_patch)
    return (
        "#!/bin/bash\n"
        "# omp self-healing wrapper (generated by install-omp-usage.py; rerun that script after omp upgrades)\n"
        "set -u\n"
        f'CLI="{cli}"\n'
        f'MARK="{MARK}"\n'
        'if [ -f "$CLI" ] && ! grep -q "$MARK" "$CLI"; then\n'
        '    python3 - "$CLI" <<\'PY\' || echo "[omp-usage] patch failed; starting unpatched omp" >&2\n'
        "import os, re, sys, tempfile\n"
        "\n"
        f"{patch_src}\n"
        # atomic write (tempfile+replace) so hard-linked bun cache copies stay pristine
        "src = open(sys.argv[1]).read()\n"
        "patched = apply_patch(src)\n"
        "mode = os.stat(sys.argv[1]).st_mode\n"
        "fd, tmp = tempfile.mkstemp(dir=os.path.dirname(sys.argv[1]), suffix='.patched')\n"
        "os.fchmod(fd, mode)\n"
        "with os.fdopen(fd, 'w') as f:\n"
        "    f.write(patched)\n"
        "os.replace(tmp, sys.argv[1])\n"
        "PY\n"
        "fi\n"
        'exec "$CLI" "$@"\n'
    )


def pick_bin_dir(cli: str, explicit: str | None) -> str:
    if explicit:
        return os.path.expanduser(explicit)
    path_dirs = [
        os.path.expanduser(d) for d in os.environ.get("PATH", "").split(os.pathsep) if d
    ]
    cli_bin_dir = os.path.dirname(os.path.realpath(shutil.which("omp") or ""))
    preferred = os.path.expanduser("~/.local/bin")
    if preferred in path_dirs and (not cli_bin_dir or path_dirs.index(preferred) < path_dirs.index(cli_bin_dir)):
        return preferred
    for d in path_dirs:
        if not cli_bin_dir or path_dirs.index(d) < path_dirs.index(cli_bin_dir):
            if os.access(d, os.W_OK):
                return d
    return preferred  # 兜底:安装后提示用户补 PATH


# ---------------------------------------------------------------- main


def main() -> None:
    ap = argparse.ArgumentParser(description="omp usage 紧凑格式自愈安装器")
    ap.add_argument("--bin-dir", help="wrapper 安装目录(默认自动)")
    ap.add_argument("--cli", help="cli.js 路径(默认自动检测)")
    args = ap.parse_args()

    if sys.platform not in ("linux", "darwin"):
        sys.exit("error: 仅支持 POSIX(bash wrapper 依赖);Windows 请用 WSL。")
    if not shutil.which("bash"):
        sys.exit("error: 未找到 bash(wrapper 依赖)。")
    if not shutil.which("python3"):
        sys.exit("error: 未找到 python3(wrapper 依赖)。")

    cli = find_cli(args.cli)
    print(f"[1/3] cli.js: {cli}")

    with open(cli, "r", encoding="utf-8", errors="replace") as f:
        src = f.read()
    if MARK in src:
        print("      已补丁,跳过。")
    else:
        original = src
        try:
            patched = apply_patch(src)
        except ValueError as e:
            sys.exit(f"error: 补丁失败: {e}(omp 结构可能已变化,请检查后手动处理)")
        # 语法校验(有 node 时);失败则回滚
        mode = os.stat(cli).st_mode
        tmp = cli + ".check.js"
        with open(tmp, "w", encoding="utf-8") as f:
            f.write(patched)
        os.chmod(tmp, mode)
        if shutil.which("node"):
            r = subprocess.run(["node", "--check", tmp], capture_output=True)
            if r.returncode != 0:
                os.unlink(tmp)
                sys.exit(f"error: 补丁后语法校验失败: {r.stderr.decode(errors='replace')[:300]}")
        os.replace(tmp, cli)
        print("      已打补丁(usage segment → 紧凑格式)。")

    bin_dir = pick_bin_dir(cli, args.bin_dir)
    os.makedirs(bin_dir, exist_ok=True)
    wrapper_path = os.path.join(bin_dir, "omp")
    script = wrapper_script(cli)
    with open(wrapper_path, "w", encoding="utf-8") as f:
        f.write(script)
    os.chmod(wrapper_path, os.stat(wrapper_path).st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    print(f"[2/3] wrapper: {wrapper_path}")

    path_dirs = [os.path.expanduser(d) for d in os.environ.get("PATH", "").split(os.pathsep) if d]
    w = shutil.which("omp")
    print(f"[3/3] `which omp` -> {w}")
    if w and os.path.realpath(w) != os.path.realpath(wrapper_path):
        print("      注意: 当前 PATH 解析到其他位置的 omp。请把", bin_dir, "放到 PATH 更前面。")
    elif bin_dir not in path_dirs:
        print(f"      注意: {bin_dir} 不在 PATH 中,需手动加入,例如:")
        print(f"        echo 'export PATH=\"{bin_dir}:$PATH\"' >> ~/.bashrc")
    print("\n完成。重启 omp 生效;omp 升级后无需手动处理(wrapper 自动重打补丁)。")


if __name__ == "__main__":
    main()
